In [133]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [134]:
df=pd.read_csv('../EDA/data/master_hotel_bookings_cleaned.csv')

In [135]:
df.shape

(87396, 47)

In [136]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,has_booking_changes,room_changed,booking_source_type,waiting_list_group,has_waiting_list,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,adr_group,adr_clean,adr_log,adr_category,requires_parking,has_special_request,special_request_category
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,1,0,Self,0,0,0,1,0,<0,0.0,0.000000,Very_Low,0,0,NaN
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,1,0,Self,0,0,0,1,0,<0,0.0,0.000000,Very_Low,0,0,NaN
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,0,1,Self,0,0,0,1,0,50-100,75.0,4.330733,Low,0,0,NaN
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,0,0,Agent,0,0,0,1,0,50-100,75.0,4.330733,Low,0,0,NaN
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,0,0,Agent,0,0,0,1,0,50-100,98.0,4.595120,Low,0,1,One

In [137]:
pd.DataFrame({
    'Column Names': df.columns,
    'Column Types': df.dtypes.values
})

                      Column Names Column Types
0                            hotel       object
1                      is_canceled        int64
2                        lead_time        int64
3                arrival_date_year        int64
4               arrival_date_month       object
5         arrival_date_week_number        int64
6        arrival_date_day_of_month        int64
7          stays_in_weekend_nights        int64
8             stays_in_week_nights        int64
9                           adults        int64
10                        children      float64
11                          babies        int64
12                            meal       object
13                         country       object
14                  market_segment       object
15            distribution_channel       object
16               is_repeated_guest        int64
17          previous_cancellations        int64
18  previous_bookings_not_canceled        int64
19              reserved_room_type       object
20              assigned_room_type       object
21                 booking_changes        int64
22                    deposit_type       object
23                           agent      float64
24                         company      float64
25            days_in_waiting_list        int64
26                   customer_type       object
27                             adr      float64
28     required_car_parking_spaces        int64
29       total_of_special_requests        int64
30              reservation_status       object
31         reservation_status_date       object
32             has_booking_changes        int64
33                    room_changed        int64
34             booking_source_type       object
35              waiting_list_group       object
36                has_waiting_list        int64
37             customer_type_Group        int64
38         customer_type_Transient        int64
39   customer_type_Transient-Party        int64
40                       adr_group       object
41                       adr_clean      float64
42                         adr_log      float64
43                    adr_category       object
44                requires_parking        int64
45             has_special_request        int64
46        special_request_category       object

In [138]:
# Create binary domestic traveler flag
df['is_domestic'] = (df['country'] == 'PRT').astype(int)

In [139]:
# 1. Map month names to numbers (1 - 12)
month_map = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4,
    'May': 5, 'June': 6, 'July': 7, 'August': 8,
    'September': 9, 'October': 10, 'November': 11, 'December': 12
}
month_num = df['arrival_date_month'].map(month_map)

# 2. Apply Sin & Cos Cyclical Encoding
df['arrival_month_sin'] = np.sin(2 * np.pi * month_num / 12)
df['arrival_month_cos'] = np.cos(2 * np.pi * month_num / 12)

In [140]:
df['total_stay_nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
df['is_weekend_only'] = (
    (df['stays_in_week_nights'] == 0) & (df['stays_in_weekend_nights'] > 0)
).astype(int)

In [141]:
# 1. Total party size
df['total_guests'] = df['adults'] + df['children'].fillna(0) + df['babies']

# 2. Family flag (strong commitment signal)
df['has_babies'] = (df['babies'] > 0).astype(int)
df['is_family'] = ((df['children'] > 0) | (df['babies'] > 0)).astype(int)

In [142]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,has_booking_changes,room_changed,booking_source_type,waiting_list_group,has_waiting_list,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,adr_group,adr_clean,adr_log,adr_category,requires_parking,has_special_request,special_request_category,is_domestic,arrival_month_sin,arrival_month_cos,total_stay_nights,is_weekend_only,total_guests,has_babies,is_family
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,1,0,Self,0,0,0,1,0,<0,0.0,0.000000,Very_Low,0,0,NaN,1,-0.5,-0.866025,0,0,2.0,0,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,1,0,Self,0,0,0,1,0,<0,0.0,0.000000,Very_Low,0,0,NaN,1,-0.5,-0.866025,0,0,2.0,0,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,0,1,Self,0,0,0,1,0,50-100,75.0,4.330733,Low,0,0,NaN,0,-0.5,-0.866025,1,0,1.0,0,0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,0,0,Agent,0,0,0,1,0,50-100,75.0,4.330733,Low,0,0,NaN,0,-0.5,-0.866025,1,0,1.0,0,0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,0,0,Agent,0,0,0,1,0,50-100,98.0,4.595120,Low,0,1,One,0,-0.5,-0.866025,2,0,2.0,0,0

In [143]:
tree_df_cols = [
    # Target
    'is_canceled',
    
    # Raw Categoricals (Pass directly to CatBoost cat_features or encode fresh)
    'hotel',
    'arrival_date_month',
    'meal',
    'market_segment',
    'deposit_type',
    'customer_type',
    'booking_source_type',
    
    # Continuous & Counts
    'lead_time',
    'adr_log',
    'total_stay_nights',
    'total_guests',
    'adults',
    'total_of_special_requests',
    'previous_cancellations',
    'previous_bookings_not_canceled',
    
    # Binary Flags
    'requires_parking',
    'room_changed',
    'has_booking_changes',
    'has_waiting_list',
    'is_domestic',
    'is_weekend_only',
    'has_babies',
    'is_family'
]

In [144]:
linear_df_cols = [
    # Target
    'is_canceled',
    
    # Cyclical Month Signals (Smooth continuity)
    'arrival_month_sin',
    'arrival_month_cos',
    
    # Raw Categoricals to One-Hot Encode fresh (pd.get_dummies)
    'hotel',
    'meal',
    'market_segment',
    'deposit_type',
    'customer_type',
    'booking_source_type',
    
    # Continuous & Counts (To scale with StandardScaler)
    'lead_time',
    'adr_log',
    'total_stay_nights',
    'total_guests',
    'adults',
    'total_of_special_requests',
    'previous_cancellations',
    'previous_bookings_not_canceled',
    
    # Binary Flags
    'requires_parking',
    'room_changed',
    'has_booking_changes',
    'has_waiting_list',
    'is_domestic',
    'is_weekend_only',
    'has_babies',
    'is_family'
]

# CAT-BOOST

In [145]:
df_tree = df[tree_df_cols].copy()

In [146]:
# Fill numeric columns with median, and text columns with mode
for col in df_tree.columns:
    if df_tree[col].dtype in ['int64', 'float64']:
        df_tree[col].fillna(df_tree[col].median(), inplace=True)
    else:
        df_tree[col].fillna(df_tree[col].mode()[0], inplace=True)

print("Null count:", df_tree.isnull().sum().sum())

C:\Users\dipk6\AppData\Local\Temp\ipykernel_9736\4185406012.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_tree[col].fillna(df_tree[col].median(), inplace=True)
C:\Users\dipk6\AppData\Local\Temp\ipykernel_9736\4185406012.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_tree[col].fillna(df_tree[col].mode()[0], inplace=True)

Null count: 0

In [147]:
print("Tree DataFrame Shape:", df_tree.shape)

Tree DataFrame Shape: (87396, 24)

In [148]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, RocCurveDisplay
from catboost import CatBoostClassifier
import matplotlib.pyplot as plt

X = df_tree.drop(columns=['is_canceled'])
y = df_tree['is_canceled']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.20, 
    random_state=42, 
    stratify=y
)

print(f"X_train: {X_train.shape} | X_test: {X_test.shape}")
print(f"Train class balance:\n{y_train.value_counts(normalize=True)}")

X_train: (69916, 23) | X_test: (17480, 23)
Train class balance:
is_canceled
0    0.725099
1    0.274901
Name: proportion, dtype: float64

In [149]:
# 1. Define categorical column names
cat_features = [
    'hotel', 
    'arrival_date_month', 
    'meal', 
    'market_segment', 
    'deposit_type', 
    'customer_type', 
    'booking_source_type'
]

# 2. Ensure string data type
for col in cat_features:
    X_train[col] = X_train[col].astype(str)
    X_test[col] = X_test[col].astype(str)

In [150]:
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.metrics import (
    roc_auc_score, 
    classification_report, 
    precision_recall_curve, 
    f1_score, 
    accuracy_score,
    precision_score,   # ◄ Added
    recall_score       # ◄ Added
)

# 1. Initialize Model
final_cat_model = CatBoostClassifier(
    depth=10,
    learning_rate=0.05,
    l2_leaf_reg=7,
    iterations=1000,
    cat_features=cat_features,
    eval_metric='AUC',
    loss_function='Logloss',
    task_type='GPU',
    random_seed=42,
    verbose=0,
)

# 2. Fit Model
final_cat_model.fit(
    X_train, y_train,
    eval_set=(X_test, y_test),
    early_stopping_rounds=50,
    verbose=0
)

# 3. Predict Probabilities & Compute ROC-AUC
y_pred_proba = final_cat_model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_pred_proba)

# 4. Find Best Probability Threshold (Maximizing F1-Score)
precisions, recalls, thresholds = precision_recall_curve(y_test, y_pred_proba)
f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-10)
best_idx = np.argmax(f1_scores)
best_threshold = thresholds[best_idx]
best_f1 = f1_scores[best_idx]

# 5. Predictions at Default (0.5) vs Optimal Threshold
y_pred_default = (y_pred_proba >= 0.5).astype(int)
y_pred_optimal = (y_pred_proba >= best_threshold).astype(int)

# 6. Summary Comparison DataFrame (Default vs Optimal Threshold)
summary_df = pd.DataFrame([
    {
        'Model': 'CatBoost',
        'Threshold': 0.50,
        'ROC-AUC': round(roc_auc, 4),
        'Accuracy': round(accuracy_score(y_test, y_pred_default), 4),
        'Precision': round(precision_score(y_test, y_pred_default), 4),
        'Recall': round(recall_score(y_test, y_pred_default), 4),
        'F1-Score': round(f1_score(y_test, y_pred_default), 4)
    },
    {
        'Model': 'CatBoost (Tuned Threshold)',
        'Threshold': round(best_threshold, 4),
        'ROC-AUC': round(roc_auc, 4),
        'Accuracy': round(accuracy_score(y_test, y_pred_optimal), 4),
        'Precision': round(precision_score(y_test, y_pred_optimal), 4),
        'Recall': round(recall_score(y_test, y_pred_optimal), 4),
        'F1-Score': round(f1_score(y_test, y_pred_optimal), 4)
    }
])

# 7. Detailed Classification Report DataFrame (Optimal Threshold)
report_dict = classification_report(y_test, y_pred_optimal, output_dict=True)
detailed_report_df = pd.DataFrame(report_dict).transpose().round(4)

# Display DataFrames
print("=== Summary Performance Table ===")
display(summary_df)

print("\n=== Detailed Classification Report (Optimal Threshold) ===")
display(detailed_report_df)

Default metric period is 5 because AUC is/are not implemented for GPU

=== Summary Performance Table ===

,Model,Threshold,ROC-AUC,Accuracy,Precision,Recall,F1-Score
0,CatBoost,0.5000,0.903,0.8386,0.7367,0.6422,0.6862
1,CatBoost (Tuned Threshold),0.3537,0.903,0.8284,0.6608,0.7717,0.7120

=== Detailed Classification Report (Optimal Threshold) ===

              precision  recall  f1-score     support
0                0.9076  0.8499    0.8778  12675.0000
1                0.6608  0.7717    0.7120   4805.0000
accuracy         0.8284  0.8284    0.8284      0.8284
macro avg        0.7842  0.8108    0.7949  17480.0000
weighted avg     0.8398  0.8284    0.8322  17480.0000