In [1]:
print("Kernel is working")

Kernel is working

In [1]:
import sys
print(sys.executable)

c:\Users\Sanji\anaconda3\python.exe

In [2]:
print("Jupyter is working")

Jupyter is working

In [3]:
import pandas as pd
import numpy as np

df_master = pd.read_csv(
    "../master_hotel_bookings_cleaned.csv"
)

print("Dataset loaded successfully!")
print("Shape:", df_master.shape)

Dataset loaded successfully!
Shape: (87396, 47)

In [4]:
print("Rows:", df_master.shape[0])
print("Columns:", df_master.shape[1])

print("\nColumn names:")
for i, col in enumerate(df_master.columns, start=1):
    print(i, col)

Rows: 87396
Columns: 47

Column names:
1 hotel
2 is_canceled
3 lead_time
4 arrival_date_year
5 arrival_date_month
6 arrival_date_week_number
7 arrival_date_day_of_month
8 stays_in_weekend_nights
9 stays_in_week_nights
10 adults
11 children
12 babies
13 meal
14 country
15 market_segment
16 distribution_channel
17 is_repeated_guest
18 previous_cancellations
19 previous_bookings_not_canceled
20 reserved_room_type
21 assigned_room_type
22 booking_changes
23 deposit_type
24 agent
25 company
26 days_in_waiting_list
27 customer_type
28 adr
29 required_car_parking_spaces
30 total_of_special_requests
31 reservation_status
32 reservation_status_date
33 has_booking_changes
34 room_changed
35 booking_source_type
36 waiting_list_group
37 has_waiting_list
38 customer_type_Group
39 customer_type_Transient
40 customer_type_Transient-Party
41 adr_group
42 adr_clean
43 adr_log
44 adr_category
45 requires_parking
46 has_special_request
47 special_request_category

In [5]:
df_master.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,adr_group,adr_clean,adr_log,adr_category,requires_parking,has_special_request,special_request_category
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,1,0,<0,0.0,0.000000,Very_Low,0,0,NaN
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,1,0,<0,0.0,0.000000,Very_Low,0,0,NaN
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,1,0,50-100,75.0,4.330733,Low,0,0,NaN
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,1,0,50-100,75.0,4.330733,Low,0,0,NaN
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,1,0,50-100,98.0,4.595120,Low,0,1,One

In [6]:
for i, col in enumerate(df_master.columns, start=1):
    print(f"{i:02d}. {col}")

01. hotel
02. is_canceled
03. lead_time
04. arrival_date_year
05. arrival_date_month
06. arrival_date_week_number
07. arrival_date_day_of_month
08. stays_in_weekend_nights
09. stays_in_week_nights
10. adults
11. children
12. babies
13. meal
14. country
15. market_segment
16. distribution_channel
17. is_repeated_guest
18. previous_cancellations
19. previous_bookings_not_canceled
20. reserved_room_type
21. assigned_room_type
22. booking_changes
23. deposit_type
24. agent
25. company
26. days_in_waiting_list
27. customer_type
28. adr
29. required_car_parking_spaces
30. total_of_special_requests
31. reservation_status
32. reservation_status_date
33. has_booking_changes
34. room_changed
35. booking_source_type
36. waiting_list_group
37. has_waiting_list
38. customer_type_Group
39. customer_type_Transient
40. customer_type_Transient-Party
41. adr_group
42. adr_clean
43. adr_log
44. adr_category
45. requires_parking
46. has_special_request
47. special_request_category

In [7]:
df_master.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
has_booking_changes                 int64
room_changed                        int64
booking_source_type                object
waiting_list_group                 object
has_waiting_list                    int64
customer_type_Group                 int64
customer_type_Transient             int64
customer_type_Transient-Party       int64
adr_group                          object
adr_clean                         float64
adr_log                           float64
adr_category                       object
requires_parking                    int64
has_special_request                 int64
special_request_category           object
dtype: object

In [8]:
print("Numeric columns:")
print(df_master.select_dtypes(include=np.number).columns.tolist())

print("\nCategorical/Object columns:")
print(df_master.select_dtypes(include="object").columns.tolist())

Numeric columns:
['is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'booking_changes', 'agent', 'company', 'days_in_waiting_list', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'has_booking_changes', 'room_changed', 'has_waiting_list', 'customer_type_Group', 'customer_type_Transient', 'customer_type_Transient-Party', 'adr_clean', 'adr_log', 'requires_parking', 'has_special_request']

Categorical/Object columns:
['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment', 'distribution_channel', 'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type', 'reservation_status', 'reservation_status_date', 'booking_source_type', 'waiting_list_group', 'adr_group', 'adr_category', 'special_request_category']

In [9]:
missing = df_master.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

company                     82137
special_request_category    43894
agent                       12193
adr_clean                       1
adr_log                         1
adr_category                    1
dtype: int64

In [10]:
print(df_master["is_canceled"].value_counts())
print("\nPercentage:")
print(
    df_master["is_canceled"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

is_canceled
0    63371
1    24025
Name: count, dtype: int64

Percentage:
is_canceled
0    72.51
1    27.49
Name: proportion, dtype: float64

In [11]:
drop_cols = [
    "is_canceled",
    "reservation_status",
    "reservation_status_date"
]

In [12]:
drop_cols = [
    "is_canceled",
    "reservation_status",
    "reservation_status_date",
    "assigned_room_type",
    "room_changed"
]

X = df_master.drop(columns=drop_cols)
y = df_master["is_canceled"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (87396, 42)
y shape: (87396,)

In [13]:
# Treat agent and company as categorical IDs

categorical_cols = [
    "hotel",
    "arrival_date_month",
    "meal",
    "country",
    "market_segment",
    "distribution_channel",
    "reserved_room_type",
    "deposit_type",
    "customer_type",
    "booking_source_type",
    "waiting_list_group",
    "adr_group",
    "adr_category",
    "special_request_category",
    "agent",
    "company"
]

print("Number of categorical features:", len(categorical_cols))

Number of categorical features: 16

In [14]:
for col in categorical_cols:
    print(
        f"{col:30} "
        f"unique={df_master[col].nunique(dropna=True):5} "
        f"missing={df_master[col].isna().sum():5}"
    )

hotel                          unique=    2 missing=    0
arrival_date_month             unique=   12 missing=    0
meal                           unique=    5 missing=    0
country                        unique=  177 missing=    0
market_segment                 unique=    8 missing=    0
distribution_channel           unique=    5 missing=    0
reserved_room_type             unique=   10 missing=    0
deposit_type                   unique=    3 missing=    0
customer_type                  unique=    4 missing=    0
booking_source_type            unique=    4 missing=    0
waiting_list_group             unique=    5 missing=    0
adr_group                      unique=    7 missing=    0
adr_category                   unique=    6 missing=    1
special_request_category       unique=    3 missing=43894
agent                          unique=  333 missing=12193
company                        unique=  352 missing=82137

In [16]:
# Columns that should NOT be used as predictors

drop_cols = [
    "is_canceled",              # Target
    "reservation_status",       # Leakage
    "reservation_status_date",  # Leakage
    "assigned_room_type",      # Potential post-booking information
    "room_changed"              # Derived from room assignment change
]

X = df_master.drop(columns=drop_cols)
y = df_master["is_canceled"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (87396, 42)
y shape: (87396,)

In [17]:
categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

numeric_features = X.select_dtypes(
    include=[np.number]
).columns.tolist()

# Agent and company are IDs, so treat them as categorical
categorical_features.extend(["agent", "company"])

# Remove them from numeric features
numeric_features = [
    col for col in numeric_features
    if col not in ["agent", "company"]
]

print("Categorical features:", len(categorical_features))
print(categorical_features)

print("\nNumeric features:", len(numeric_features))
print(numeric_features)

Categorical features: 16
['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment', 'distribution_channel', 'reserved_room_type', 'deposit_type', 'customer_type', 'booking_source_type', 'waiting_list_group', 'adr_group', 'adr_category', 'special_request_category', 'agent', 'company']

Numeric features: 26
['lead_time', 'arrival_date_year', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'booking_changes', 'days_in_waiting_list', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'has_booking_changes', 'has_waiting_list', 'customer_type_Group', 'customer_type_Transient', 'customer_type_Transient-Party', 'adr_clean', 'adr_log', 'requires_parking', 'has_special_request']

In [22]:
X_model = X.copy()

# Categorical columns
for col in categorical_features:
    X_model[col] = (
        X_model[col]
        .fillna("Unknown")
        .astype(str)
    )

# Numerical columns
for col in numeric_features:
    X_model[col] = X_model[col].fillna(
        X_model[col].median()
    )

print("Remaining missing values:",
      X_model.isna().sum().sum())

Remaining missing values: 0

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

Training set: (69916, 42)
Test set: (17480, 42)

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            ),
            categorical_features
        ),
        (
            "numeric",
            "passthrough",
            numeric_features
        )
    ]
)

In [26]:
X_train_encoded = preprocessor.fit_transform(X_train)

X_test_encoded = preprocessor.transform(X_test)

print("Encoded training shape:", X_train_encoded.shape)
print("Encoded test shape:", X_test_encoded.shape)

Encoded training shape: (69916, 922)
Encoded test shape: (17480, 922)

In [27]:
from lightgbm import LGBMClassifier

lgbm_model = LGBMClassifier(
    objective="binary",
    random_state=42,
    n_jobs=-1
)

lgbm_model.fit(
    X_train_encoded,
    y_train
)

print("LightGBM training completed.")

[LightGBM] [Info] Number of positive: 19220, number of negative: 50696
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.080373 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1955
[LightGBM] [Info] Number of data points in the train set: 69916, number of used features: 326
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.274901 -> initscore=-0.969896
[LightGBM] [Info] Start training from score -0.969896
LightGBM training completed.

In [28]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

lgbm_pred = lgbm_model.predict(X_test_encoded)
lgbm_prob = lgbm_model.predict_proba(X_test_encoded)[:, 1]

print("LightGBM Baseline Results")
print("-" * 30)
print("Accuracy :", round(accuracy_score(y_test, lgbm_pred), 4))
print("Precision:", round(precision_score(y_test, lgbm_pred), 4))
print("Recall   :", round(recall_score(y_test, lgbm_pred), 4))
print("F1 Score :", round(f1_score(y_test, lgbm_pred), 4))
print("ROC-AUC  :", round(roc_auc_score(y_test, lgbm_prob), 4))

LightGBM Baseline Results
------------------------------
Accuracy : 0.8436
Precision: 0.7423
Recall   : 0.6606
F1 Score : 0.699
ROC-AUC  : 0.9121

c:\Users\Sanji\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\Sanji\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [29]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train_encoded,
    y_train
)

print("XGBoost training completed.")

XGBoost training completed.

In [30]:
xgb_pred = xgb_model.predict(X_test_encoded)
xgb_prob = xgb_model.predict_proba(X_test_encoded)[:, 1]

print("XGBoost Baseline Results")
print("-" * 30)
print("Accuracy :", round(accuracy_score(y_test, xgb_pred), 4))
print("Precision:", round(precision_score(y_test, xgb_pred), 4))
print("Recall   :", round(recall_score(y_test, xgb_pred), 4))
print("F1 Score :", round(f1_score(y_test, xgb_pred), 4))
print("ROC-AUC  :", round(roc_auc_score(y_test, xgb_prob), 4))

XGBoost Baseline Results
------------------------------
Accuracy : 0.8434
Precision: 0.7407
Recall   : 0.6618
F1 Score : 0.6991
ROC-AUC  : 0.9096

In [31]:
from sklearn.model_selection import RandomizedSearchCV

lgbm_params = {
    "learning_rate": [0.01, 0.05, 0.1],
    "n_estimators": [100, 200, 500],
    "max_depth": [4, 6, 8],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

lgbm_base = LGBMClassifier(
    objective="binary",
    random_state=42,
    n_jobs=-1,
    verbosity=-1
)

lgbm_search = RandomizedSearchCV(
    estimator=lgbm_base,
    param_distributions=lgbm_params,
    n_iter=20,
    scoring="roc_auc",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

lgbm_search.fit(X_train_encoded, y_train)

print("Best parameters:")
print(lgbm_search.best_params_)

print("\nBest CV ROC-AUC:")
print(round(lgbm_search.best_score_, 4))

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best parameters:
{'subsample': 0.8, 'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.1, 'colsample_bytree': 1.0}

Best CV ROC-AUC:
0.9142

In [32]:
best_lgbm = lgbm_search.best_estimator_

lgbm_tuned_pred = best_lgbm.predict(X_test_encoded)
lgbm_tuned_prob = best_lgbm.predict_proba(
    X_test_encoded
)[:, 1]

print("Tuned LightGBM Results")
print("-" * 30)

print("Accuracy :",
      round(accuracy_score(y_test, lgbm_tuned_pred), 4))

print("Precision:",
      round(precision_score(y_test, lgbm_tuned_pred), 4))

print("Recall   :",
      round(recall_score(y_test, lgbm_tuned_pred), 4))

print("F1 Score :",
      round(f1_score(y_test, lgbm_tuned_pred), 4))

print("ROC-AUC  :",
      round(roc_auc_score(y_test, lgbm_tuned_prob), 4))

c:\Users\Sanji\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\Sanji\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Tuned LightGBM Results
------------------------------
Accuracy : 0.8503
Precision: 0.7511
Recall   : 0.6814
F1 Score : 0.7145
ROC-AUC  : 0.917

In [33]:
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV

xgb_params = {
    "learning_rate": [0.01, 0.05, 0.1],
    "n_estimators": [100, 200, 500],
    "max_depth": [4, 6, 8],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

xgb_base = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb_search = RandomizedSearchCV(
    estimator=xgb_base,
    param_distributions=xgb_params,
    n_iter=20,
    scoring="roc_auc",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

xgb_search.fit(X_train_encoded, y_train)

print("Best XGBoost parameters:")
print(xgb_search.best_params_)

print("\nBest CV ROC-AUC:")
print(round(xgb_search.best_score_, 4))

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best XGBoost parameters:
{'subsample': 0.8, 'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.1, 'colsample_bytree': 1.0}

Best CV ROC-AUC:
0.9162

In [34]:
best_xgb = xgb_search.best_estimator_

xgb_tuned_pred = best_xgb.predict(X_test_encoded)
xgb_tuned_prob = best_xgb.predict_proba(X_test_encoded)[:, 1]

print("Tuned XGBoost Results")
print("-" * 30)

print("Accuracy :", round(accuracy_score(y_test, xgb_tuned_pred), 4))
print("Precision:", round(precision_score(y_test, xgb_tuned_pred), 4))
print("Recall   :", round(recall_score(y_test, xgb_tuned_pred), 4))
print("F1 Score :", round(f1_score(y_test, xgb_tuned_pred), 4))
print("ROC-AUC  :", round(roc_auc_score(y_test, xgb_tuned_prob), 4))

Tuned XGBoost Results
------------------------------
Accuracy : 0.8544
Precision: 0.7575
Recall   : 0.6918
F1 Score : 0.7232
ROC-AUC  : 0.9191

In [35]:
model_comparison = pd.DataFrame({
    "Model": [
        "LightGBM Baseline",
        "LightGBM Tuned",
        "XGBoost Baseline",
        "XGBoost Tuned"
    ],
    "Accuracy": [
        0.8436,
        0.8503,
        0.8434,
        0.8544
    ],
    "Precision": [
        0.7423,
        0.7511,
        0.7407,
        0.7575
    ],
    "Recall": [
        0.6606,
        0.6814,
        0.6618,
        0.6918
    ],
    "F1 Score": [
        0.6990,
        0.7145,
        0.6991,
        0.7232
    ],
    "ROC-AUC": [
        0.9121,
        0.9170,
        0.9096,
        0.9191
    ]
})

model_comparison

               Model  Accuracy  Precision  Recall  F1 Score  ROC-AUC
0  LightGBM Baseline    0.8436     0.7423  0.6606    0.6990   0.9121
1     LightGBM Tuned    0.8503     0.7511  0.6814    0.7145   0.9170
2   XGBoost Baseline    0.8434     0.7407  0.6618    0.6991   0.9096
3      XGBoost Tuned    0.8544     0.7575  0.6918    0.7232   0.9191

In [36]:
import joblib

best_xgb = xgb_search.best_estimator_

joblib.dump(
    best_xgb,
    "best_xgboost_model.pkl"
)

print("Champion XGBoost model saved successfully.")

Champion XGBoost model saved successfully.

In [37]:
import json

xgb_config = {
    "model": "XGBoost Classifier",
    "best_parameters": xgb_search.best_params_,
    "cv_roc_auc": round(xgb_search.best_score_, 4),
    "test_accuracy": 0.8544,
    "test_precision": 0.7575,
    "test_recall": 0.6918,
    "test_f1": 0.7232,
    "test_roc_auc": 0.9191
}

with open("xgboost_best_config.json", "w") as f:
    json.dump(xgb_config, f, indent=4)

print("XGBoost configuration saved.")

XGBoost configuration saved.

In [39]:
# Get feature names after preprocessing
feature_names = preprocessor.get_feature_names_out()

# Create feature importance DataFrame
feature_importance = pd.DataFrame({
    "feature": feature_names,
    "importance": best_xgb.feature_importances_
})

# Sort by importance
feature_importance = feature_importance.sort_values(
    "importance",
    ascending=False
).reset_index(drop=True)

# Show top 20 features
feature_importance.head(20)

                                          feature  importance
0            numeric__required_car_parking_spaces    0.093913
1            categorical__deposit_type_Non Refund    0.054557
2           categorical__market_segment_Online TA    0.044680
3                        categorical__country_PRT    0.035322
4   categorical__special_request_category_Unknown    0.024790
5                          categorical__agent_7.0    0.022310
6            categorical__deposit_type_No Deposit    0.021054
7                          categorical__agent_9.0    0.017552
8                        categorical__agent_240.0    0.016073
9                       categorical__adr_group_<0    0.016015
10                        categorical__agent_11.0    0.013243
11           categorical__customer_type_Transient    0.012936
12             categorical__market_segment_Direct    0.012686
13                numeric__previous_cancellations    0.011939
14        categorical__distribution_channel_TA/TO    0.011904
15                       categorical__country_AGO    0.009335
16                       categorical__agent_241.0    0.009171
17      categorical__market_segment_Offline TA/TO    0.008011
18                     numeric__arrival_date_year    0.007859
19                       categorical__country_CHN    0.006775

In [40]:
feature_importance.head(20)

                                          feature  importance
0            numeric__required_car_parking_spaces    0.093913
1            categorical__deposit_type_Non Refund    0.054557
2           categorical__market_segment_Online TA    0.044680
3                        categorical__country_PRT    0.035322
4   categorical__special_request_category_Unknown    0.024790
5                          categorical__agent_7.0    0.022310
6            categorical__deposit_type_No Deposit    0.021054
7                          categorical__agent_9.0    0.017552
8                        categorical__agent_240.0    0.016073
9                       categorical__adr_group_<0    0.016015
10                        categorical__agent_11.0    0.013243
11           categorical__customer_type_Transient    0.012936
12             categorical__market_segment_Direct    0.012686
13                numeric__previous_cancellations    0.011939
14        categorical__distribution_channel_TA/TO    0.011904
15                       categorical__country_AGO    0.009335
16                       categorical__agent_241.0    0.009171
17      categorical__market_segment_Offline TA/TO    0.008011
18                     numeric__arrival_date_year    0.007859
19                       categorical__country_CHN    0.006775